"""
rag/chain.py
LangChain LCEL RAG chain for billing error explanation.

Initialized once at app startup via init_chain(app). Call explain_detection()
per request to generate a grounded plain-English explanation with citations.

Design decisions:
- Module-level singletons (_vectorstore, _chain) avoid rebuilding the vectorstore
  on every request — ChromaDB client and embedding model are expensive to init.
- Citations are extracted from retrieved doc metadata (document_title, page_number),
  not generated by the LLM, so they are always grounded in actual retrieved chunks.
- max_tokens=300 enforces the 300-token output guardrail (DevGuide requirement).
- temperature=0 ensures deterministic, factual responses.
- MODULE_SOURCE_ALLOWLIST scopes retrieval per module: NCCI Chapter 1 for duplicate
  charges, RVU26B for Medicare rate outliers, NSA docs for EOB and NSA modules.
"""

import logging

from langchain_community.vectorstores import Chroma
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

logger = logging.getLogger(__name__)

EMBEDDING_MODEL = "text-embedding-3-small"
COLLECTION_NAME = "medicheck_kb"

# Maps each Service 2 module name to the document titles it is allowed to retrieve from.
# Modules not listed here fall back to an unfiltered search across all sources.
MODULE_SOURCE_ALLOWLIST: dict[str, list[str]] = {
    "duplicate_charge": [
        "CMS NCCI Chapter 1 — General Correct Coding Policies",
    ],
    "medicare_rate_outlier": [
        "CMS Physician Fee Schedule: File Layout and Rate Calculation Methodology (2026)",
    ],
    "eob_reconciliation": [
        "No Surprises Act at a Glance",
        "Helping Consumers Protect Their Rights Under the No Surprises Act",
        "No Surprises Act: Overview of Key Consumer Protections",
        "Requirements Related to Surprise Billing: Final Rules Fact Sheet",
    ],
    "no_surprises_act": [
        "No Surprises Act at a Glance",
        "Helping Consumers Protect Their Rights Under the No Surprises Act",
        "No Surprises Act: Overview of Key Consumer Protections",
        "Requirements Related to Surprise Billing: Final Rules Fact Sheet",
    ],
}

EXPLAIN_PROMPT = ChatPromptTemplate.from_template(
    """You are a medical billing compliance expert helping a patient understand a potential error on their bill.

Error type: {error_type}
Detected issue: {description}

Relevant regulatory and coding guidance:
{context}

Explain this billing error to the patient in plain English in 2-4 sentences.
State what was found and why it may be incorrect based on the guidance above.
Base your answer only on the provided context. If the context does not address the error, say so briefly.
Do not speculate beyond what the context supports."""
)

EXPLAIN_PROMPT_MEDICARE = ChatPromptTemplate.from_template(
    """You are a medical billing compliance expert helping a patient understand a potential error on their bill.

Error type: {error_type}
Detected issue: {description}

Relevant regulatory and coding guidance:
{context}

The detected issue above already states the billed amount, the Medicare reference rate, the percentage ratio, and the outlier threshold — do not repeat any of these figures or thresholds.
Write 3-5 sentences of plain conversational prose explaining: how the CMS Physician Fee Schedule establishes the expected payment amount using RVUs and the conversion factor (citing specific values from the context where available); why a charge this far above that calculated rate may indicate overbilling; and one concrete step the patient can take to dispute the charge.
Base your answer only on the provided context. If the context does not address the error, say so briefly.
Do not speculate beyond what the context supports."""
)

EXPLAIN_MODULE_PROMPT_MEDICARE = ChatPromptTemplate.from_template(
    """You are a medical billing compliance expert helping a patient understand a potential error on their bill.

Error type: {error_type}

Relevant regulatory and coding guidance:
{context}

Write 3-5 sentences of plain conversational prose explaining: how the CMS Physician Fee Schedule establishes the expected payment amount using RVUs and the conversion factor (citing specific values from the context where available); why charges significantly above the Medicare rate may indicate overbilling; and one concrete step the patient can take to dispute such a charge.
Base your answer only on the provided context. If the context does not address the error, say so briefly.
Do not speculate beyond what the context supports."""
)

LETTER_PROMPT = ChatPromptTemplate.from_template(
    """You are a medical billing compliance expert drafting a formal dispute paragraph for a patient's billing dispute letter.

Patient: {patient_name}
Provider: {provider_name}
Total disputed amount: ${total_savings}

Billing errors identified:
{error_summary}

Relevant regulatory context:
{context}

Write a single formal dispute paragraph (3-5 sentences) that:
- Requests the provider review and correct the identified errors
- References the applicable regulations from the context above
- States the total adjustment requested
- Mentions that escalation to the state insurance commissioner is possible if unresolved within 30 days

Write only the paragraph text. Do not include a salutation, subject line, or closing."""
)

# Module-level singletons — initialized once by init_chain()
_vectorstore = None
_top_k: int = 3
_chain = None
_medicare_chain = None
_medicare_module_chain = None
_letter_chain = None


def is_ready() -> bool:
    return _vectorstore is not None and _chain is not None


def _sanitize(text: str, max_length: int) -> str:
    """Truncate and strip control characters from OCR-originated text before
    using as an embedding query or LLM prompt variable."""
    return " ".join(str(text)[:max_length].split())


def init_chain(app) -> None:
    """
    Initialize the RAG vectorstore and LCEL chain from Flask app config.
    Must be called once during app startup (from create_app).
    """
    global _vectorstore, _top_k, _chain, _medicare_chain, _medicare_module_chain, _letter_chain

    embeddings = OpenAIEmbeddings(
        model=EMBEDDING_MODEL,
        api_key=app.config["OPENAI_API_KEY"],
    )

    _vectorstore = Chroma(
        collection_name=COLLECTION_NAME,
        persist_directory=app.config["CHROMA_PERSIST_PATH"],
        embedding_function=embeddings,
    )

    _top_k = app.config["RAG_TOP_K"]

    llm = ChatOpenAI(
        model=app.config["OPENAI_MODEL"],
        temperature=0,
        max_tokens=500,
        api_key=app.config["OPENAI_API_KEY"],
    )

    _chain = EXPLAIN_PROMPT | llm | StrOutputParser()
    _medicare_chain = EXPLAIN_PROMPT_MEDICARE | llm | StrOutputParser()
    _medicare_module_chain = EXPLAIN_MODULE_PROMPT_MEDICARE | llm | StrOutputParser()
    _letter_chain = LETTER_PROMPT | llm | StrOutputParser()

    logger.info(
        "RAG chain initialized (model=%s, top_k=%d, db=%s)",
        app.config["OPENAI_MODEL"],
        _top_k,
        app.config["CHROMA_PERSIST_PATH"],
    )


def explain_detection(detection: dict) -> dict:
    """
    Run the RAG chain for a single DetectionResult dict.

    Retrieves the top-k most relevant chunks from ChromaDB, builds context,
    generates a plain-English explanation via GPT-4o-mini, and extracts
    source citations from the retrieved chunk metadata.

    Args:
        detection: DetectionResult serialized as dict. Must contain at minimum:
                   error_type (str), description (str), module (str).

    Returns:
        The same dict with 'explanation' (str) and 'citations' (list[str]) populated.

    Raises:
        RuntimeError: If called before init_chain().
    """
    if _vectorstore is None or _chain is None:
        raise RuntimeError("RAG chain is not initialized. Call init_chain(app) first.")

    module = detection.get("module", "")
    chain = _medicare_chain if module == "medicare_rate_outlier" else _chain

    error_type = _sanitize(detection["error_type"], 100)
    description = _sanitize(detection["description"], 500)
    query = f"{error_type}: {description}"

    allowed_sources = MODULE_SOURCE_ALLOWLIST.get(module)
    source_filter = (
        {"document_title": {"$in": allowed_sources}} if allowed_sources else None
    )

    if allowed_sources is not None:
        logger.debug(
            "Module '%s' — restricting retrieval to %d sources",
            module,
            len(allowed_sources),
        )
        docs = _vectorstore.similarity_search(query, k=_top_k, filter=source_filter)
    else:
        logger.warning(
            "Module '%s' has no source allowlist — skipping retrieval, returning empty context",
            module,
        )
        docs = []

    context = "\n\n".join(doc.page_content for doc in docs)

    explanation = chain.invoke(
        {
            "error_type": error_type,
            "description": description,
            "context": context,
        }
    )

    # Build deduplicated citations as objects matching the API contract:
    # { "source": document_title, "section": section/page, "url": null }
    seen: set[str] = set()
    citations: list[dict] = []
    for doc in docs:
        source = doc.metadata.get("document_title") or doc.metadata.get(
            "source", "Unknown"
        )
        page = doc.metadata.get("page_number", "")
        section = doc.metadata.get("section", "")
        section_label = section or (f"p. {page}" if page else "")
        if source not in seen:
            seen.add(source)
            citations.append({"source": source, "section": section_label, "url": None})

    return {
        **detection,
        "explanation": explanation,
        "citations": citations,
    }


def explain_module_context(module: str) -> dict:
    """
    Generate a shared module-level explanation for all errors of the same module type.

    Called once per unique module when multiple errors share a module — avoids near-duplicate
    regulatory context text appearing on adjacent error cards. Does not reference specific
    CPT codes or amounts; those are already shown in each card's description.

    Args:
        module: Service 2 module name (e.g. "medicare_rate_outlier").

    Returns:
        Dict with 'explanation' (str) and 'citations' (list[dict]).

    Raises:
        RuntimeError: If called before init_chain().
    """
    if _vectorstore is None or _medicare_module_chain is None:
        raise RuntimeError("RAG chain is not initialized. Call init_chain(app) first.")

    allowed_sources = MODULE_SOURCE_ALLOWLIST.get(module)
    query = "Medicare physician fee schedule RVU conversion factor payment rate calculation"
    source_filter = (
        {"document_title": {"$in": allowed_sources}} if allowed_sources else None
    )

    if allowed_sources is not None:
        logger.debug(
            "Module context '%s' — restricting retrieval to %d sources",
            module,
            len(allowed_sources),
        )
        docs = _vectorstore.similarity_search(query, k=_top_k, filter=source_filter)
    else:
        logger.warning(
            "Module '%s' has no source allowlist — skipping retrieval", module
        )
        docs = []

    context = "\n\n".join(doc.page_content for doc in docs)

    explanation = _medicare_module_chain.invoke(
        {"error_type": "Medicare Rate Outlier", "context": context}
    )

    seen: set[str] = set()
    citations: list[dict] = []
    for doc in docs:
        source = doc.metadata.get("document_title") or doc.metadata.get(
            "source", "Unknown"
        )
        page = doc.metadata.get("page_number", "")
        section = doc.metadata.get("section", "")
        section_label = section or (f"p. {page}" if page else "")
        if source not in seen:
            seen.add(source)
            citations.append({"source": source, "section": section_label, "url": None})

    return {"explanation": explanation, "citations": citations}


def draft_letter_content(analysis: dict) -> str:
    """
    Generate the formal dispute paragraph for the billing dispute letter.

    Retrieves regulatory context from ChromaDB using the detected error types
    as the query, then generates a grounded dispute paragraph via GPT-4o-mini.

    Args:
        analysis: dict from Service 2 containing patient_name, provider_name,
                  date_of_service, errors (list), total_estimated_savings.

    Returns:
        A single plain-text dispute paragraph string.

    Raises:
        RuntimeError: If called before init_chain().
    """
    if _vectorstore is None or _letter_chain is None:
        raise RuntimeError("RAG chain is not initialized. Call init_chain(app) first.")

    errors = analysis.get("errors", [])

    # Build retrieval query from all detected error types
    error_types = " ".join(e.get("error_type", "") for e in errors)
    query = f"billing dispute: {error_types}"

    # No source filter for the letter — it covers all modules and needs broad context
    docs = _vectorstore.similarity_search(query, k=_top_k)
    context = "\n\n".join(doc.page_content for doc in docs)

    # Summarise errors for the prompt
    error_lines = []
    for e in errors:
        impact = e.get("estimated_dollar_impact", 0.0)
        error_lines.append(f"- {e.get('error_type', 'Billing Error')}: ${impact:,.2f}")
    error_summary = (
        "\n".join(error_lines) if error_lines else "- Billing errors detected"
    )

    return _letter_chain.invoke(
        {
            "patient_name": analysis.get("patient_name", "[Patient]"),
            "provider_name": analysis.get("provider_name", "[Provider]"),
            "total_savings": f"{analysis.get('total_estimated_savings', 0.0):,.2f}",
            "error_summary": error_summary,
            "context": context,
        }
    )
