"""
rag/chain.py
LangChain LCEL RAG chain for billing error explanation.

Initialized once at app startup via init_chain(app). Call explain_detection()
per request to generate a grounded plain-English explanation with citations.

Design decisions:
- Module-level singletons (_retriever, _chain) avoid rebuilding the vectorstore
  on every request — ChromaDB client and embedding model are expensive to init.
- Citations are extracted from retrieved doc metadata (document_title, page_number),
  not generated by the LLM, so they are always grounded in actual retrieved chunks.
- max_tokens=300 enforces the 300-token output guardrail (DevGuide requirement).
- temperature=0 ensures deterministic, factual responses.
"""

import logging

from langchain_community.vectorstores import Chroma
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

logger = logging.getLogger(__name__)

EMBEDDING_MODEL = "text-embedding-3-small"
COLLECTION_NAME = "medicheck_kb"

EXPLAIN_PROMPT = ChatPromptTemplate.from_template(
    """You are a medical billing compliance expert helping a patient understand a potential error on their bill.

Error type: {error_type}
Detected issue: {description}

Relevant regulatory and coding guidance:
{context}

Explain this billing error to the patient in plain English in 2-4 sentences.
State what was found and why it may be incorrect based on the guidance above.
Base your answer only on the provided context. If the context does not address the error, say so briefly.
Do not speculate beyond what the context supports."""
)

LETTER_PROMPT = ChatPromptTemplate.from_template(
    """You are a medical billing compliance expert drafting a formal dispute paragraph for a patient's billing dispute letter.

Patient: {patient_name}
Provider: {provider_name}
Total disputed amount: ${total_savings}

Billing errors identified:
{error_summary}

Relevant regulatory context:
{context}

Write a single formal dispute paragraph (3-5 sentences) that:
- Requests the provider review and correct the identified errors
- References the applicable regulations from the context above
- States the total adjustment requested
- Mentions that escalation to the state insurance commissioner is possible if unresolved within 30 days

Write only the paragraph text. Do not include a salutation, subject line, or closing."""
)

# Module-level singletons — initialized once by init_chain()
_retriever = None
_chain = None
_letter_chain = None


def init_chain(app) -> None:
    """
    Initialize the RAG retriever and LCEL chain from Flask app config.
    Must be called once during app startup (from create_app).
    """
    global _retriever, _chain, _letter_chain

    embeddings = OpenAIEmbeddings(
        model=EMBEDDING_MODEL,
        api_key=app.config["OPENAI_API_KEY"],
    )

    vectorstore = Chroma(
        collection_name=COLLECTION_NAME,
        persist_directory=app.config["CHROMA_PERSIST_PATH"],
        embedding_function=embeddings,
    )

    _retriever = vectorstore.as_retriever(
        search_type="similarity",
        search_kwargs={"k": app.config["RAG_TOP_K"]},
    )

    llm = ChatOpenAI(
        model=app.config["OPENAI_MODEL"],
        temperature=0,
        max_tokens=300,
        api_key=app.config["OPENAI_API_KEY"],
    )

    _chain = EXPLAIN_PROMPT | llm | StrOutputParser()
    _letter_chain = LETTER_PROMPT | llm | StrOutputParser()

    logger.info(
        "RAG chain initialized (model=%s, top_k=%d, db=%s)",
        app.config["OPENAI_MODEL"],
        app.config["RAG_TOP_K"],
        app.config["CHROMA_PERSIST_PATH"],
    )


def explain_detection(detection: dict) -> dict:
    """
    Run the RAG chain for a single DetectionResult dict.

    Retrieves the top-k most relevant chunks from ChromaDB, builds context,
    generates a plain-English explanation via GPT-4o-mini, and extracts
    source citations from the retrieved chunk metadata.

    Args:
        detection: DetectionResult serialized as dict. Must contain at minimum:
                   error_type (str), description (str), module (str).

    Returns:
        The same dict with 'explanation' (str) and 'citations' (list[str]) populated.

    Raises:
        RuntimeError: If called before init_chain().
    """
    if _retriever is None or _chain is None:
        raise RuntimeError("RAG chain is not initialized. Call init_chain(app) first.")

    query = f"{detection['error_type']}: {detection['description']}"

    docs = _retriever.invoke(query)

    context = "\n\n".join(doc.page_content for doc in docs)

    explanation = _chain.invoke(
        {
            "error_type": detection["error_type"],
            "description": detection["description"],
            "context": context,
        }
    )

    # Build deduplicated citations as objects matching the API contract:
    # { "source": document_title, "section": section/page, "url": null }
    seen: set[str] = set()
    citations: list[dict] = []
    for doc in docs:
        source = doc.metadata.get("document_title") or doc.metadata.get("source", "Unknown")
        page = doc.metadata.get("page_number", "")
        section = doc.metadata.get("section", "")
        section_label = section or (f"p. {page}" if page else "")
        if source not in seen:
            seen.add(source)
            citations.append({"source": source, "section": section_label, "url": None})

    return {
        **detection,
        "explanation": explanation,
        "citations": citations,
    }


def draft_letter_content(analysis: dict) -> str:
    """
    Generate the formal dispute paragraph for the billing dispute letter.

    Retrieves regulatory context from ChromaDB using the detected error types
    as the query, then generates a grounded dispute paragraph via GPT-4o-mini.

    Args:
        analysis: dict from Service 2 containing patient_name, provider_name,
                  date_of_service, errors (list), total_estimated_savings.

    Returns:
        A single plain-text dispute paragraph string.

    Raises:
        RuntimeError: If called before init_chain().
    """
    if _retriever is None or _letter_chain is None:
        raise RuntimeError("RAG chain is not initialized. Call init_chain(app) first.")

    errors = analysis.get("errors", [])

    # Build retrieval query from all detected error types
    error_types = " ".join(e.get("error_type", "") for e in errors)
    query = f"billing dispute: {error_types}"

    docs = _retriever.invoke(query)
    context = "\n\n".join(doc.page_content for doc in docs)

    # Summarise errors for the prompt
    error_lines = []
    for e in errors:
        impact = e.get("estimated_dollar_impact", 0.0)
        error_lines.append(f"- {e.get('error_type', 'Billing Error')}: ${impact:,.2f}")
    error_summary = "\n".join(error_lines) if error_lines else "- Billing errors detected"

    return _letter_chain.invoke(
        {
            "patient_name": analysis.get("patient_name", "[Patient]"),
            "provider_name": analysis.get("provider_name", "[Provider]"),
            "total_savings": f"{analysis.get('total_estimated_savings', 0.0):,.2f}",
            "error_summary": error_summary,
            "context": context,
        }
    )
